{{- if or (and .Values.config.twitch.clientId .Values.config.twitch.clientSecret) .Values.config.webhook.secret .Values.config.discord.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stitch.fullname" . }}-secret
  labels:
    {{- include "stitch.labels" . | nindent 4 }}
type: Opaque
data:
{{- if and .Values.config.twitch.clientId .Values.config.twitch.clientSecret }}
  TWITCH_CLIENT_ID: {{ .Values.config.twitch.clientId | b64enc }}
  TWITCH_CLIENT_SECRET: {{ .Values.config.twitch.clientSecret | b64enc }}
{{- end }}
{{- if .Values.config.webhook.secret }}
  WEBHOOK_SECRET: {{ .Values.config.webhook.secret | b64enc }}
{{- end }}
{{- if .Values.config.discord.token }}
  DISCORD_TOKEN: {{ .Values.config.discord.token | b64enc }}
{{- end }}
{{- end }}
