apiVersion: v1
kind: Service
metadata:
  name: {{ include "stitch.fullname" . }}
  labels:
    {{- include "stitch.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ default .Values.config.server.port .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.config.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "stitch.selectorLabels" . | nindent 4 }}
