[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tonic-prost-build = "0.14.0"
prost-build = "0.14.1"

[dependencies]
tonic = { workspace = true }
tonic-prost = "0.14.0"
prost = { workspace = true }
prost-types = { workspace = true }
